name: SubcategoriesForCAP
version: "2020.10-02"
license: "GPL-2.0-or-later"
date: 2020-10-18
description: |
    Subcategory and other related constructors for CAP categories

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2020.02.16"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "MonoidalCategories"
      version: ">= 2020.03.01"
      url: "https://homalg-project.github.io/CAP_project/MonoidalCategories"
    - name: "CategoryConstructor"
      version: ">= 2020.10-02"
      url: "https://homalg-project.github.io/CategoryConstructor"

suggested-pkgs:
    - name: "Toposes"
      version: ">= 2020.02.19"
      url: "https://homalg-project.github.io/Toposes"
    - name: "FreydCategoriesForCAP"
      version: ">= 2019.11.02"
      url: "https://github.com/homalg-project/CAP_project/tree/master/FreydCategoriesForCAP"

www: https://homalg-project.github.io/SubcategoriesForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/SubcategoriesForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/SubcategoriesForCAP/releases/download/v2020.10-02/SubcategoriesForCAP-2020.10-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/SubcategoriesForCAP/releases/download/v2020.10-02/SubcategoriesForCAP-2020.10-02.zip

pdf: https://github.com/homalg-project/SubcategoriesForCAP/releases/download/v2020.10-02/SubcategoriesForCAP-2020.10-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BKS20</span>]   <b class='BibAuthor'>Barakat, M., Kuhmichel, T. and Saleh, K.</b>,
     <i class='BibTitle'>SubcategoriesForCAP, Subcategory and other related constructors for CAP categories,
             Version 2020.10-02</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/SubcategoriesForCAP">https://homalg-project.github.io/SubcategoriesForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ SubcategoriesForCAP2020.10-02,
      author =           {Barakat, M. and Kuhmichel, T. and Saleh, K.},
      title =            {{SubcategoriesForCAP},  Subcategory  and other related
                          constructors for CAP categories, {V}ersion 2020.10-02},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/SubcategoriesForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{SubcategoriesForCAP}}},
      printedkey =       {BKS20}
    }

