name: SubcategoriesForCAP
version: "2021.12-02"
license: "GPL-2.0-or-later"
date: 2021-12-26
description: |
    Subcategory and other related constructors for CAP categories

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/
    - name: Tom Kuhmichel
      url: https://github.com/TKuh
    - name: Kamal Saleh
      url: https://github.com/kamalsaleh/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "CAP"
      version: ">= 2021.11-04"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "CompilerForCAP"
      version: ">= 2021.10-03"
      url: "https://homalg-project.github.io/pkg/CompilerForCAP"
    - name: "MonoidalCategories"
      version: ">= 2020.03.01"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "CategoryConstructor"
      version: ">= 2021.12-03"
      url: "https://homalg-project.github.io/pkg/CategoryConstructor"

suggested-pkgs:
    - name: "Toposes"
      version: ">= 2020.02.19"
      url: "https://homalg-project.github.io/pkg/Toposes"
    - name: "FreydCategoriesForCAP"
      version: ">= 2019.11.02"
      url: "https://homalg-project.github.io/pkg/FreydCategoriesForCAP"

www: https://homalg-project.github.io/pkg/SubcategoriesForCAP
readme: README.md
packageinfo: https://homalg-project.github.io/SubcategoriesForCAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/SubcategoriesForCAP/releases/download/v2021.12-02/SubcategoriesForCAP-2021.12-02.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/SubcategoriesForCAP/releases/download/v2021.12-02/SubcategoriesForCAP-2021.12-02.zip

pdf: https://github.com/homalg-project/SubcategoriesForCAP/releases/download/v2021.12-02/SubcategoriesForCAP-2021.12-02.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BKS21</span>]   <b class='BibAuthor'>Barakat, M., Kuhmichel, T. and Saleh, K.</b>,
     <i class='BibTitle'>SubcategoriesForCAP, Subcategory and other related constructors for CAP categories,
             Version 2021.12-02</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/SubcategoriesForCAP">https://homalg-project.github.io/pkg/SubcategoriesForCAP</a></span>.
    </p>
    

bibtex: |
    @misc{ SubcategoriesForCAP2021.12-02,
      author =           {Barakat, M. and Kuhmichel, T. and Saleh, K.},
      title =            {{SubcategoriesForCAP},  Subcategory  and other related
                          constructors for CAP categories, {V}ersion 2021.12-02},
      month =            {Dec},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/SubcategoriesForCAP}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{SubcategoriesForCAP}}},
      printedkey =       {BKS21}
    }

